### ISSUE TITLE
Question about evaluation codes.

### ISSUE THREAD

**Issue by suoych** [guhur/hiveformer#2]
Hi, thanks for sharing your work, may I ask whether the eval.py or the network.py is correct?
I followed the steps in the instructions and trained a model using your code. When I was going to evaluate the model, I met many errors raised in the eval.py file. Many of the classes are not defined such as PlainUNet, TransformerUNet.
So are the eval.py and network.py correct?

**Comment by suoych** [comment]
BTW I ran into this error during testing.
![image](https://user-images.githubusercontent.com/29878050/199179200-328e2503-8ba7-49a6-a88f-5b3e6bc6721d.png)
It affects the success rate and I don't know what caused it. I will be grateful if anyone can help me with it. Thanks.

**Comment by vaesong** [comment]
> Hi, thanks for sharing your work, may I ask whether the eval.py or the network.py is correct? I followed the steps in the instructions and trained a model using your code. When I was going to evaluate the model, I met many errors raised in the eval.py file. Many of the classes are not defined such as PlainUNet, TransformerUNet. So are the eval.py and network.py correct?

Hi, I have the same problem, many of the classes are not defined such as PlainUNet, TransformerUNet.How did you solve it?

**Comment by guhur** [comment]
Sorry, my cleaning step has been wrongful. Can you refer to my original code in the ` raw`  branch?
