### ISSUE TITLE
Question about the keypoint selection when generating data

### ISSUE THREAD

**Issue by mxu34** [guhur/hiveformer#5]
Hi, thanks for sharing the code.

I noticed that when generating the data with data_gen.py, you first filter the frames based on the keypoint_discoverty function. It filters out most of the frames and leaves around three frames (~100 -> 3) in the open drawer env. What is the motivation for using the keypoint_discovery? Will only keeping the key points cause trouble at the test time, considering that there will be lots of unseen frames or frames that are not keyframes?

The line that I am referring to is: https://github.com/guhur/hiveformer/blob/69dc6eecee549adf0c5cbbd51c6c4d27c5f5d001/data_gen.py#L55

**Comment by berniewang8177** [comment]
> 

I have a similar question. According to the paper, the keypoint_discovery is named "macro steps" in the paper, which is a technique introduced in "Q-Attention: Enabling efficient learning for vision-based robotic manipulation".

In the paper, the author claims to use an an inverse-kinematics based controller to find a trajectory between macro-steps".
Could author provides some guidance how to find this inverse-kinematics controller?

**Comment by guhur** [comment]
> What is the motivation for using the keypoint_discovery? Will only keeping the key points cause trouble at the test time, considering that there will be lots of unseen frames or frames that are not keyframes?

Using macro steps instead of micro steps is very useful to avoid overfitting. You need to use the macro steps during testing.

>  Could author provides some guidance how to find this inverse-kinematics controller?
IK is done internally in RLBench. For real experiments, I used MoveIt!
