### ISSUE TITLE
no t_dict and z_dict

### ISSUE THREAD

**Issue by JF-TY** [guhur/hiveformer#7]
I trained a model. When I was going to test it, there was no weight in the model_dict in eval.py. When I changed it to state_dict, it could be used, but the model_dict didn’t have t and z. Did I miss something?
![image](https://user-images.githubusercontent.com/52477703/219959893-e282c6fe-cc50-4711-96ac-fb6d4ba70ea5.png)
![image](https://user-images.githubusercontent.com/52477703/219959972-e1560ce0-945b-4b39-a486-48d49c1aa63d.png)
![image](https://user-images.githubusercontent.com/52477703/219960052-873bd754-87bf-4ad0-9857-f6f3e5c2d11c.png)

**Comment by guhur** [comment]
Can you test with the branch `raw` instead of the `main`? Following discussions with other research teams, they were able to reproduce results using this branch.
