### ISSUE TITLE
About the seeds

### ISSUE THREAD

**Issue by QianJiu-0325** [guhur/hiveformer#8]
Hi, thank you very much for being able to share the code, I would like to ask what is the purpose of setting multiple seeds during training? In the article it says：To reduce the impact of the imperfect motion planner, we run the motion planner with different seeds up to 10 times until it finds a trajectory to the target。Can the test metrics of the paper be achieved if training is done using 1 seed? @guhur

**Comment by guhur** [comment]
The variance in the results is HUGE. To provide repeatable results, it is paramount to use different seeds.

**Comment by QianJiu-0325** [comment]
Hello. I have one more question, how many cross attention blocks do you use? and about how long does it take to train a single task? I would appreciate it if you could answer my question. Thank you.
